name: quickcare_employee_app
description: An Application for QuickCare Employee
publish_to: "none"
version: ..+1
environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  dio: ^5.1.0
  get_it: ^7.3.0
  shared_preferences: ^2.1.0
  go_router: ^6.5.8
  logger: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mockito: ^5.4.0
  http_mock_adapter: ^0.4.2
  build_runner: ^2.3.3
  flutter_flavorizr: ^2.1.6

flutter:
  uses-material-design: true
flavorizr:
  flavors:
    dev:
      app:
        name: "Quick Care Dev"
      android:
        applicationId: "au.quick_care.terem.dev"
      ios:
        bundleId: "au.quick_care.terem.dev"

    prod:
      app:
        name: "Quick Care"
      android:
        applicationId: "au.quick_care.terem.prod"
      ios:
        bundleId: "au.quick_care.terem.prod"
