# Ran whenever a pull request to be merged in main is created or updated.
name: Flutter analyze
on:
  pull_request:
    branches:
      - main
    paths:
      - "frontend/**"

  workflow_call:
    inputs:
      new-pubspec-version:
        required: true
        type: string

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: 'echo "current version: ${{ inputs.new-pubspec-version }}"'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"
          cache: true

      - name: Analyze linting check
        run: flutter analyze --fatal-warnings --fatal-infos
