# Ran whenever a pull request to be merged in main is created or updated.
name: Flutter analyze
on:
  pull_request:
    branches:
      - main
    paths:
      - "frontend/**"

  workflow_call:
    inputs:
      flutter-version:
        required: true
        type: string
        description: "Flutter version to use"

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "${{ inputs.flutter-version }}"
          channel: "stable"
          cache: true

      - name: Analyze linting check
        working-directory: ./frontend
        run: flutter analyze --fatal-warnings --fatal-infos
