name: Android Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'
      
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.10.6'
          channel: 'stable'
          cache: true
          
      - name: Get flutter dependencies
        run: flutter pub get
      
      - name: Build Android release
        run: flutter build apk --release --flavor=dev --split-per-abi